### ISSUE TITLE
found 2 high severity vulnerabilities

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser3-project-template#22]
audited 10448 packages in 6.202s
found 2 high severity vulnerabilities

run `npm audit fix` to fix them, or `npm audit` for details

**Comment by calrrox** [comment]
Today more than 276 high severity vulnerabilities :smile: 

![image](https://user-images.githubusercontent.com/4570712/68521301-19c5a080-0276-11ea-9bd6-91e233b25518.png)

maybe one solution is no versioning `package-lock.json`

**Comment by photonstorm** [comment]
And how many of them _actually matter_ for entirely client-side games?

**Comment by Spayco** [comment]
@photonstorm simply remove the `package-lock.json` and most (all in my case) of these problems will be gone
