### ISSUE TITLE
JavaScript Standard Style

### ISSUE THREAD

**Issue by EvoluoGames** [photonstorm/phaser3-project-template#3]
Hi again,

what do you think about use [JavaScript Standard Style](https://standardjs.com/)?

**Comment by photonstorm** [comment]
I don't think there is any point being strict about editor configs in a project template - the whole point is you're free to code how you like, using the template to start off with. As far as I'm concerned I think we'll keep the Editor configs for the main library (and examples) to ensure contributors keep to the same style, but in here you can structure it however you like.

**Comment by EvoluoGames** [comment]
:+1:
