### ISSUE TITLE
Doesn't work on iOS (iPhone, iPad)

### ISSUE THREAD

**Issue by zvermafia** [photonstorm/phaser3-project-template#33]
I'm workin on iMac and everything works fine on it. I tried to play on my android phone and everything worked fine too (I added ` --host 0.0.0.0` flag to the npm scripts' start command to access to the game from LAN).

Then I tried to play the game on my iPad but it didn't work (I just see background color but game doesn't start), also tried on simulators iPhone 11 X Pro and iPad 2 on my iMac the result is the same as on my real iPad. On my iPad I looked google chrome console logs (with `chrome://inspect`) and there weren't any errors...

What is the problem and how to fix it?

**Comment by stahlmanDesign** [comment]
I haven't looked but I've seen this happen in other game engines and it's often due to audio files that are not supported on iOS / Safari, such as .ogg

**Comment by zvermafia** [comment]
I'm closing the issue due to the fact that it was a long time ago and in the near future I'm not going to work with Phaser because I'm busy with other things.
