### ISSUE TITLE
CleanWebpackPlugin.root is not a valid option

### ISSUE THREAD

**Issue by tylerlong** [photonstorm/phaser3-project-template#34]
```
    new CleanWebpackPlugin({
      root: path.resolve(__dirname, "../")
    }),
```

But `root` is not a supported option at all: 

https://github.com/johnagan/clean-webpack-plugin/blob/master/src/clean-webpack-plugin.ts#L7-L65

**Comment by photonstorm** [comment]
This is fixed with v2.0.0 of this template.
