### ISSUE TITLE
Cannot build the project

### ISSUE THREAD

**Issue by Jooseba** [photonstorm/phaser3-project-template#46]
Hi, 

The project wont build up with npm run build, all I get is "TypeErrpr: merge is not a function". I tried to google some answers but did not find any solution.

Any idea why getting this error?

**Comment by yougotwill** [comment]
Check out the `prod.js` file in this PR might help. https://github.com/photonstorm/phaser3-project-template/pull/40/files

**Comment by photonstorm** [comment]
This is fixed with v2.0.0 of this template.
