### ISSUE TITLE
could you make this repo as a template repository?

### ISSUE THREAD

**Issue by bassochette** [photonstorm/phaser3-project-template#76]
I'd like to start a project from this template.
With a template repository I could juste create a new repo from this one (without forking).

It would keep a link to this template and all open project built from the template would be explicitly displayed on this repo.
It would build a galery of project ;)

**Comment by LukeWolfGames** [comment]
I second this. It seems like permissions to this template have changed so we can no longer access it to create a template to start a project.

**Comment by photonstorm** [comment]
This has been done.
